# Generated by Django 4.2.11 on 2024-03-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Název filmu')),
                ('rate', models.IntegerField(blank=True, null=True, verbose_name='Hodnocení')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Čas vložení')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
